EMS/EMS/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EMS.Controllers
{
    public class ContactUsController : Controller
    {
        // GET: ContactUs
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ContactUs()
        {
            return View();
        }

    }
}

EMS/EMS/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using System.Web.Helpers;
using EMS.Models;

namespace EMS.Controllers
{

    [Authorize]
    public class EmployeesController : Controller
    {
        private EmpDatabaseEntities db = new EmpDatabaseEntities();

        // GET: Employees
        public ActionResult Index(int page = 1, string sort = "Emp_First_Name", string sortdir = "asc", string search = "")
        {
            int pageSize = 5;
            int totalRecord = 0;
            if (page < 1) page = 1;
            int skip = (page * pageSize) - pageSize;
            var data = GetEmployees(search, sort, sortdir, skip, pageSize, out totalRecord);
            ViewBag.TotalRows = totalRecord;
            ViewBag.search = search;
            return View(data);
        }

        public List<Employee> GetEmployees(string search, string sort, string sortdir, int skip, int pageSize, out int totalRecord)
        {

            var v = (from a in db.Employees
                     where
                             a.Emp_First_Name.Contains(search) ||
                             a.Emp_Last_Name.Contains(search) ||
                             a.Emp_Home_Address.Contains(search) ||
                             a.Emp_Grade.Contains(search) ||
                             a.Emp_Designation.Contains(search)
                     select a
                            );
            totalRecord = v.Count();
            v = v.OrderBy(sort + " " + sortdir);
            if (pageSize > 0)
            {
                v = v.Skip(skip).Take(pageSize);
            }
            return v.ToList();
        }

        // GET: Employees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            ViewBag.Emp_Dept_ID = new SelectList(db.Departments, "Dept_ID", "Dept_Name");
            ViewBag.Emp_Grade = new SelectList(db.Grade_master, "Grade_Code", "Grade_Code");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Emp_ID,Emp_First_Name,Emp_Last_Name,Emp_Date_of_Birth,Emp_Date_of_Joining,Emp_Dept_ID,Emp_Grade,Emp_Designation,Emp_Salary,Emp_Gender,Emp_Marital_Status,Emp_Home_Address,Emp_Contact_Num")] Employee employee)
        {

            if (db.Employees.Any(d => d.Emp_ID == employee.Emp_ID ))
            {
                ModelState.AddModelError("Emp_ID", "Employee ID already exists.");
            }
            if (ModelState.IsValid)
            {
                db.Employees.Add(employee);
                db.SaveChanges();
                TempData["AlertMessage"] = "Employee Added Successfully....!";
                return RedirectToAction("Index");
            }

            ViewBag.Emp_Dept_ID = new SelectList(db.Departments, "Dept_ID", "Dept_Name", employee.Emp_Dept_ID);
            ViewBag.Emp_Grade = new SelectList(db.Grade_master, "Grade_Code", "Description", employee.Emp_Grade);
            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.Emp_Dept_ID = new SelectList(db.Departments, "Dept_ID", "Dept_Name", employee.Emp_Dept_ID);
            ViewBag.Emp_Grade = new SelectList(db.Grade_master, "Grade_Code", "Grade_Code", employee.Emp_Grade);
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Emp_ID,Emp_First_Name,Emp_Last_Name,Emp_Date_of_Birth,Emp_Date_of_Joining,Emp_Dept_ID,Emp_Grade,Emp_Designation,Emp_Salary,Emp_Gender,Emp_Marital_Status,Emp_Home_Address,Emp_Contact_Num,Status")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                //Employee e = new Employee();
                //e.Status = "Active";
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                TempData["AlertMessage"] = "Employee Updated Successfully....!";
                return RedirectToAction("Index");
            }
            ViewBag.Emp_Dept_ID = new SelectList(db.Departments, "Dept_ID", "Dept_Name", employee.Emp_Dept_ID);
            ViewBag.Emp_Grade = new SelectList(db.Grade_master, "Grade_Code", "Description", employee.Emp_Grade);
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employees.Find(id);
            if (employee != null)
            {
                if (employee.Status == "Active")
                {
                    employee.Status = "Inactive";
                    db.SaveChanges();
                }
                //else
                //{
                //    TempData["AlertMessage"] = "Employee status is already Inactive.";
                //}

                else if (employee.Status == "Inactive")
                {
                    employee.Status = "Active";
                    db.SaveChanges();
                }
                else
                {
                    employee.Status = "Inactive";
                    db.SaveChanges();
                }
            }
            //db.Employees.Remove(employee);
            //db.SaveChanges();
            else {
                TempData["AlertMessage"] = "Employee Deleted Successfully....!";
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EMS/EMS/Controllers/Grade_masterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EMS.Models;

namespace EMS.Controllers
{
    public class Grade_masterController : Controller
    {
        private EmpDatabaseEntities db = new EmpDatabaseEntities();

        // GET: Grade_master
        public ActionResult Index()
        {
            return View(db.Grade_master.ToList());
        }

        // GET: Grade_master/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grade_master grade_master = db.Grade_master.Find(id);
            if (grade_master == null)
            {
                return HttpNotFound();
            }
            return View(grade_master);
        }

        // GET: Grade_master/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Grade_master/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Grade_Code,Description,Min_Salary,Max_Salary")] Grade_master grade_master)
        {

            if (db.Grade_master.Any(d => d.Grade_Code == grade_master.Grade_Code))
            {
                ModelState.AddModelError("Grade_Code", "Grade Code already exists.");
            }
            if (ModelState.IsValid)
            {
                db.Grade_master.Add(grade_master);
                db.SaveChanges();
                TempData["AlertMessage"] = "Grade Added Successfully....!";
                return RedirectToAction("Index");
            }

            return View(grade_master);
        }

        // GET: Grade_master/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grade_master grade_master = db.Grade_master.Find(id);
            if (grade_master == null)
            {
                return HttpNotFound();
            }
            return View(grade_master);
        }

        // POST: Grade_master/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Grade_Code,Description,Min_Salary,Max_Salary")] Grade_master grade_master)
        {
            if (ModelState.IsValid)
            {
                db.Entry(grade_master).State = EntityState.Modified;
                db.SaveChanges();
                TempData["AlertMessage"] = "Grade Updated Successfully....!";
                return RedirectToAction("Index");
            }
            return View(grade_master);
        }

        // GET: Grade_master/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grade_master grade_master = db.Grade_master.Find(id);
            if (grade_master == null)
            {
                return HttpNotFound();
            }
            return View(grade_master);
        }

        // POST: Grade_master/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public ActionResult DeleteConfirmed(string id)
        {
            try
            {
                Grade_master grade_master = db.Grade_master.Find(id);

                // Check if the grade_master has any dependencies
                if (HasDependencies(grade_master))
                {
                    string alertMessage = "Cannot delete the grade because it belongs to certain employees.";
                    return Content($"<script>alert('{alertMessage}'); window.location.href = '/Grade_master/Index';</script>");
                }

                // If there are no dependencies, proceed with deletion
                db.Grade_master.Remove(grade_master);
                db.SaveChanges();
                TempData["AlertMessage"] = "Grade Deleted Successfully....!";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while deleting the grade.");
                return View();
            }
        }

        // Method to check if the grade has dependencies
        private bool HasDependencies(Grade_master grade_master)
        {
            // Check if the grade_master is associated with any employees
            return db.Employees.Any(e => e.Emp_Grade == grade_master.Grade_Code);
        }

        //public ActionResult DeleteConfirmed(string id)
        //{



        //    Grade_master grade_master = db.Grade_master.Find(id);
        //    db.Grade_master.Remove(grade_master);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EMS/EMS/Views/Shared/_EmpLayout.cshtml
@{
    ViewBag.Title = "_EmpLayout";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Employee Management System", "Index", "Employees", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Employees")</li>
                    @*<li>@Html.ActionLink("Create", "Create", "Employees")</li>*@
                    <li>@Html.ActionLink("Grade", "Index", "Grade_master")</li>
                    <li>@Html.ActionLink("Departments", "Index", "Departments")</li>
                    <li>@Html.ActionLink("Holidays", "Index", "Holidays")</li>
                    <li>@Html.ActionLink("Contact Us", "Index", "ContactUs")</li>



                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a>Dear - @User.Identity.Name</a></li>
                        <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Account")</li>
                    }
                </ul>







                @*@using (Html.BeginForm("Search", "Employee", FormMethod.Post, new { id = "searchForm" }))
                            {
                                <div class="form-group">
                                    @Html.Label("SearchTerm", "Search:")
                                    @Html.TextBox("searchTerm", null, new { @class = "form-control" })
                                </div>
                                <button type="submit" class="btn btn-primary">Search</button>
                            }

                            <div id="searchResults"></div>

                            @section scripts {
                                <script>
                    $(function () {
                        $('#searchForm').submit(function (event) {
                            event.preventDefault();
                            var searchTerm = $('#searchTerm').val();
                            $.ajax({
                                url: '/Employee/Search',
                                type: 'POST',
                                data: { searchTerm: searchTerm },
                                success: function (data) {
                                    $('#searchResults').html(data);
                                }
                            });
                        });
                    });
                                </script>
                            }*@




            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My EMS Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/CustomJs.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

EMS/EMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Employee Management System", "Index", "Employees", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My EMS Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/CustomJs.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>